some small improvements and a basic command line interface
0x57e11a/markdoll pull request #1
Opened 2024-09-07 19:03 UTC by LunarEclipse363

the commit messages should be fairly self explanatory, but:

- the editorconfig can be added to gitignore instead if desired
- the cli is very simple and only works with stdin/stdout for now, to use it `cargo run --features=cli`
- there is a FIXME comment left in a part of the spec where something looks missing

2024-09-07 22:23 UTC, 0x57e11a requested changes
mostly just admiration/curiosity, with a couple small changes :3

2024-09-07 22:23 UTC, 0x57e11a commented on spec.doll
> +				however, this requires that the content [//:FIXME\: what is missing here?]
![:neocat_floof_explode:](https://github.com/user-attachments/assets/3c2c512f-4615-40d3-923d-37fe0ea936de)

it believes that it was supposed to say something along the lines "however, this requires that the content is indented one level further than the tag, to let the parser know what is and is not part of the content"

oops :3

2024-09-07 22:23 UTC, 0x57e11a commented on src/main.rs
perfect! love that the stdout/stderr are separated to allow piping, and that on fail, it returns `1` <3

2024-09-07 22:23 UTC, 0x57e11a commented on README.md
> +this library requires features from rust 1.81
excuse it for being ignorant, but what features require 1.81? not a demand to change it, just curious :3

2024-09-07 22:23 UTC, 0x57e11a commented on Cargo.toml
adding `rust-version = "1.81"` should help with consistency with the README

2024-09-08 00:51 UTC, LunarEclipse363 commented on README.md
> +this library requires features from rust 1.81
IIRC it was reasons for `#![allow...]`

When I first tried running cargo check with 1.79, it was also missing the `Default` impl for `Rc<str>`, not sure if that was added in 1.80 or 1.81 though.

2024-09-08 04:19 UTC, 0x57e11a commented on README.md
> +this library requires features from rust 1.81
sounds good! just curious!

2024-09-08 04:20 UTC, 0x57e11a approved these changes
beep

2024-09-08 04:20 UTC, merged